name: cd_diff_dir

on:
  issue_comment:
    types: [created, edited]

jobs:
  cd_diff_dir:
    if: ${{ (github.event.issue.pull_request) && (github.event.comment.body == '/check') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0
        with:
          fetch-depth: 0

      - name: comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
        run: |
          # actionのタイプが `issue_comment` の場合は git diff で拾えなさそう？なので gh コマンドで引いてくる
          # gh pr diff 3  | grep "diff --git" | cut -d " " -f 3 | awk 'BEGIN{FS="a/"}{print $2}'
          for f in `gh pr diff 3  | grep "diff --git" | cut -d " " -f 3 | awk 'BEGIN{FS="a/"}{print $2}'`; do \
            echo ${f} # full path
            echo ${f%/*} # dir path
          done

