name: cd_diff_dir

on:
  issue_comment:
    types: [created, edited]

jobs:
  cd_diff_dir:
    if: ${{ (github.event.issue.pull_request) && (github.event.comment.body == '/check') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0
        with:
          fetch-depth: 0

      - name: comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
        run: |
          echo "Hello World!"
          echo `git diff main --name-only`
          for f in `git diff main --name-only`; do
            echo ${f}
            pwd
            echo ${f%/*}
            cd ${f%/*}
          done
