name: Dynamic Environment

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'release target'
        required: true
        options:
          - dev
          - prd

jobs:
  release:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.event.inputs.target }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: echo
        run: |
          echo "target: ${{ github.event.inputs.target }}"
          echo "env: ${{ secrets.ENV }}"

