name: pr_comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  pr_comment:
    if: ${{ (github.event.issue.pull_request) && (github.event.comment.body == '/comment') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0

      - name: comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
        run: |
          gh pr comment ${PR_NUMBER} --body "Hello World!"
          echo "```\n" > comment.txt
          echo "Hello World!" >> comment.txt
          echo "\n```" >> comment.txt
          gh pr comment ${PR_NUMBER} -F comment.txt
