name: pr_comment

on:
  pull_request:
    branches:
      - main

  issue_comment:
    types: [created, edited]

jobs:
  pr_comment:
    if: ${{ (github.event.issue.pull_request) && (github.event.comment.body == '/comment') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0
        with:
          fetch-depth: 0

      - name: comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment --body "Hello World!"

