name: release

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: "release version (e.g. v0.0.1)"
        required: true
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: setup git
        run: |
          git config --global user.name "release-action"
          git config --global user.email "trash@ucpr.dev"

      - name: setup sember-cli
        env:
          SEMVER_CLI_VERSION: v1.1.0
        run: |
          wget https://github.com/maykonlf/semver-cli/releases/download/${SEMVER_CLI_VERSION}/semver-linux-amd64.zip
          unzip semver-linux-amd64.zip

      - name: update version
        run: |
          TARGET=${{ github.event.inputs.version }}
          if [ $TARGET = "patch" ]; then
            TARGET=release
          fi
          ./semver up ${TARGET}

      - name: push semver.yaml
        run: |
          git add .semver.yaml
          git commit -m "chore: update version"
          git push origin HEAD

      - name: create tag
        run: |
          TAG=$(./semver get release)
          git tag ${TAG}
          git push origin ${TAG}

      - name: create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(./semver get release)
          gh release create ${TAG} --generate-notes
