name: test_env

on:
  push:
    tags:
      - 'v*'

jobs:
  test_env:
    runs-on: ubuntu-latest

    environment:
      name: approve_test

    steps:
      - uses: actions/checkout@v3.0.0
      - run: echo 'Hello'
